<?php

namespace DrupalAssociation\Signify;

class Verifier
{

  protected $publicKey;

  /**
   * Verifier constructor.
   *
   * @param string $public_key
   *   A public key generated by the BSD signify application.
   */
   function __construct($public_key) {
       $this->publicKey = $public_key;
   }

  /**
   * Get the public key in use.
   *
   * @return string
   *   The public key.
   */
   public function getPublicKey(){
       return $this->publicKey;
   }
}
